osx_image: xcode7.1
language: objective-c
podfile: Demo/Podfile

env:
  global:
    - LANG=en_US.UTF-8

cache: cocoapods

xcode_workspace: Demo/Demo.xcworkspace
xcode_scheme: Demo

before_install:
  - KEY_CHAIN=ios-build.keychain
  - security create-keychain -p travis $KEY_CHAIN
  - security default-keychain -s $KEY_CHAIN
  - security unlock-keychain -p travis $KEY_CHAIN
  - security set-keychain-settings -t 3600 -u $KEY_CHAIN

script: xctool -configuration Debug -workspace Demo/Demo.xcworkspace -scheme Demo clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
